# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[gin-project-example]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql connect configuration
mysql:
  ip: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8&parseTime=true'
  db-name: 'gin-project-example'
  username: 'root'
  password: 'muserquantity'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: false

# redis configuration
redis:
  db: 0
  ip: '127.0.0.1'
  port: '6379'
  password: 'muserquantity'

# system configuration
system:
  env: 'develop'  # Change to "develop" to skip authentication for development mode, change to "public" to enable authentication
  ip: ''
  port: 8899
  db-type: 'mysql'
  oss-type: 'local'
  # IP limit count 6000000 times per hour
  iplimit-count: 6000000
  #  IP limit per hour
  iplimit-time: 3600
