// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package basic

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/MuserQuantity/gin-project-example-without-users/dal/model/system"
)

func newTestStruct(db *gorm.DB, opts ...gen.DOOption) testStruct {
	_testStruct := testStruct{}

	_testStruct.testStructDo.UseDB(db, opts...)
	_testStruct.testStructDo.UseModel(&system.TestStruct{})

	tableName := _testStruct.testStructDo.TableName()
	_testStruct.ALL = field.NewAsterisk(tableName)
	_testStruct.Test = field.NewString(tableName, "test")

	_testStruct.fillFieldMap()

	return _testStruct
}

type testStruct struct {
	testStructDo

	ALL  field.Asterisk
	Test field.String

	fieldMap map[string]field.Expr
}

func (t testStruct) Table(newTableName string) *testStruct {
	t.testStructDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t testStruct) As(alias string) *testStruct {
	t.testStructDo.DO = *(t.testStructDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *testStruct) updateTableName(table string) *testStruct {
	t.ALL = field.NewAsterisk(table)
	t.Test = field.NewString(table, "test")

	t.fillFieldMap()

	return t
}

func (t *testStruct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *testStruct) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 1)
	t.fieldMap["test"] = t.Test
}

func (t testStruct) clone(db *gorm.DB) testStruct {
	t.testStructDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t testStruct) replaceDB(db *gorm.DB) testStruct {
	t.testStructDo.ReplaceDB(db)
	return t
}

type testStructDo struct{ gen.DO }

func (t testStructDo) Debug() *testStructDo {
	return t.withDO(t.DO.Debug())
}

func (t testStructDo) WithContext(ctx context.Context) *testStructDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t testStructDo) ReadDB() *testStructDo {
	return t.Clauses(dbresolver.Read)
}

func (t testStructDo) WriteDB() *testStructDo {
	return t.Clauses(dbresolver.Write)
}

func (t testStructDo) Session(config *gorm.Session) *testStructDo {
	return t.withDO(t.DO.Session(config))
}

func (t testStructDo) Clauses(conds ...clause.Expression) *testStructDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t testStructDo) Returning(value interface{}, columns ...string) *testStructDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t testStructDo) Not(conds ...gen.Condition) *testStructDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t testStructDo) Or(conds ...gen.Condition) *testStructDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t testStructDo) Select(conds ...field.Expr) *testStructDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t testStructDo) Where(conds ...gen.Condition) *testStructDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t testStructDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *testStructDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t testStructDo) Order(conds ...field.Expr) *testStructDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t testStructDo) Distinct(cols ...field.Expr) *testStructDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t testStructDo) Omit(cols ...field.Expr) *testStructDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t testStructDo) Join(table schema.Tabler, on ...field.Expr) *testStructDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t testStructDo) LeftJoin(table schema.Tabler, on ...field.Expr) *testStructDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t testStructDo) RightJoin(table schema.Tabler, on ...field.Expr) *testStructDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t testStructDo) Group(cols ...field.Expr) *testStructDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t testStructDo) Having(conds ...gen.Condition) *testStructDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t testStructDo) Limit(limit int) *testStructDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t testStructDo) Offset(offset int) *testStructDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t testStructDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *testStructDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t testStructDo) Unscoped() *testStructDo {
	return t.withDO(t.DO.Unscoped())
}

func (t testStructDo) Create(values ...*system.TestStruct) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t testStructDo) CreateInBatches(values []*system.TestStruct, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t testStructDo) Save(values ...*system.TestStruct) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t testStructDo) First() (*system.TestStruct, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*system.TestStruct), nil
	}
}

func (t testStructDo) Take() (*system.TestStruct, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*system.TestStruct), nil
	}
}

func (t testStructDo) Last() (*system.TestStruct, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*system.TestStruct), nil
	}
}

func (t testStructDo) Find() ([]*system.TestStruct, error) {
	result, err := t.DO.Find()
	return result.([]*system.TestStruct), err
}

func (t testStructDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*system.TestStruct, err error) {
	buf := make([]*system.TestStruct, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t testStructDo) FindInBatches(result *[]*system.TestStruct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t testStructDo) Attrs(attrs ...field.AssignExpr) *testStructDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t testStructDo) Assign(attrs ...field.AssignExpr) *testStructDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t testStructDo) Joins(fields ...field.RelationField) *testStructDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t testStructDo) Preload(fields ...field.RelationField) *testStructDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t testStructDo) FirstOrInit() (*system.TestStruct, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*system.TestStruct), nil
	}
}

func (t testStructDo) FirstOrCreate() (*system.TestStruct, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*system.TestStruct), nil
	}
}

func (t testStructDo) FindByPage(offset int, limit int) (result []*system.TestStruct, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t testStructDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t testStructDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t testStructDo) Delete(models ...*system.TestStruct) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *testStructDo) withDO(do gen.Dao) *testStructDo {
	t.DO = *do.(*gen.DO)
	return t
}
